/*
 *
 * Auto-generated by scripts/generate_nice_view_art.py
 * SPDX-License-Identifier: MIT
 *
 */

#pragma once

#include <lvgl.h>

#define CUSTOM_ART_FRAME_COUNT 16
#define CUSTOM_ART_FRAME_DURATION_MS 100
#define CUSTOM_ART_ANIM_DURATION_MS (CUSTOM_ART_FRAME_COUNT * CUSTOM_ART_FRAME_DURATION_MS)

extern const lv_img_dsc_t *const custom_art_frames[CUSTOM_ART_FRAME_COUNT];
